### ISSUE TITLE
Data sharing plan - refactor and model implementation

### ISSUE THREAD

**Issue by Bankso** [mc2-center/data-models#106]
In their current state, the MC2 data sharing plans are going to become difficult to manage, as resource contributions increase. One solution is to convert the key information in the data sharing plans to a data model, which we can upload to grant-based Synapse projects.

Benefits here are pretty broad! I can see this helping with: 
- data ingress planning and tracking
- folder provisioning
- information accessibility for contributors
- content validation (likely through schematic)

This could also be tied back to the data landscape survey form - we could revamp the DLS to serve as a data sharing plan submission form. Submissions would go to Synapse, where the plan would be logged and trackable (via DFA or otherwise) and folders would be provisioned (see https://github.com/mc2-center/mc2-center-dcc/issues/54 and https://github.com/mc2-center/mc2-center-dcc/issues/55)

**Comment by Bankso** [comment]
This is in progress in data-models: https://github.com/mc2-center/data-models/tree/add-sharing-plans

**Comment by Bankso** [comment]
Refactored sharing plan consists of a schematic-compatible data model, which can be generated, validated, and uploaded to Synapse via the DCA 

DSP includes information in the [google doc table](https://docs.google.com/document/d/1PTVaxThmkZ4NmqeCIzy2bsr0RxlyINwRxCxRauF0G9Q/edit#heading=h.74ty8qzi8pqi) + Data Use Codes

For governance info related to human-derived data, I think it is best to use the google doc to define applicable DUO codes, but we should be able to encode all the info in the sharing plan

**Comment by aclayton555** [comment]
24-6 close out: this is now implemented, but some complimentary documentation updates needed. Can file related PRs for these updates, then close this
