### ISSUE TITLE
Incorporate field 'PublicationView_id' for DCA upsert testing

### ISSUE THREAD

**Issue by Bankso** [mc2-center/data-models#12]
Per this Slack thread: https://sagebionetworks.slack.com/archives/C050V2V9K9D/p1683833417512449

Currently, in order for schematic to recognize rows for upsert, a primary key feature of the pattern <component>_id must be defined within the data model. 

While this is a generalized issue that can likely be addressed with a general solution, the aim of this issue is to quickly adapt the 'PublicationView' model to include the field 'PublicationView_id', which should enable the upsert feature

**Comment by aclayton555** [comment]
@Bankso just confirming, I think this issue can be closed?

**Comment by Bankso** [comment]
@aclayton555 Yep, I'll go ahead and close this one. Thanks!
