### ISSUE TITLE
Onboarding Aditya Nath into MC2 data model

### ISSUE THREAD

**Issue by aditigopalan** [mc2-center/data-models#140]
Tracking onboarding tasks for @aditya-nath-sage:

- [x]  @aditigopalan will review the curation workflow cycle with Aditya for August/September and share the [documentation](https://docs.google.com/document/d/1bLQuKDMfkdRFD9IyKA6vpssZ_IZAzX1SF_hDverTYgM/edit?usp=sharing).
- [x]  @aditigopalan will explain the release process for the data model to Aditya.
- [ ]  @aditya-nath-sage will review the resources and post any questions here.

**Comment by aclayton555** [comment]
24-9 : Going well. Will be helping with sync and ongoing curation work. Curation workflow will be transitioning to Aditya over next sprint.

**Comment by aclayton555** [comment]
24-10: Have been working on curation workflow.

Is there an action to create tickets? No, these are duplicated
