### ISSUE TITLE
CPO-792/CPO-795 Summer 2023 grant curation-related updates to data model

### ISSUE THREAD

**Issue by aclayton555** [mc2-center/data-models#20]
Summer grant curation: https://sagebionetworks.jira.com/browse/CPO-792

@aditigopalan I added information on 2 new grants to be ingressed and displayed on the CCKP to the manifest linked in the above Jira issue. In order to ingress these and pass validation, however, we need to update the data model in a couple of places with any new terms. 

I think the summary of updates includes the following:

- [x] Add the following new grant numbers as valid values for all 'grant number' related attributes: `CA279408`, `CA279560`
- [x] Add the following as a valid value for the attribute Grant Institution Name: `University of Nevada Reno`
- [x] Add the following as a valid value for the attribute Grant Institution Alias: `UNR`

Attempting to submit the manifest might also flag some additional updates needed. @Bankso I note that this version of the GrantView manifest was from before we updated the data model with the _id fix, so if we need to pop this onto an updated version of GrantView, please let me know!

**Comment by aclayton555** [comment]
@aditigopalan can we incorporate these updates in your updates next week?

**Comment by aditigopalan** [comment]
Updates made and merged!

**Comment by aclayton555** [comment]
thanks Aditi - can you clarify, do we need to release a new version of our data model before we can proceed to ingress the manifest that necessitated these changes?

**Comment by aditigopalan** [comment]
I think it should be okay as long you have the newest version of the data model. @Bankso would you be able to confirm?

**Comment by Bankso** [comment]
A new version release isn't required, but I think we should create releases for each update. That will make it easier to update the DCA config and will help us make sure we are using the current model version and corresponding metadata templates.

For versioning (I think this is how Verena and Brynn were doing this previously):

- Schema additions/modifications should be major versions (3.0.0 -> 4.0.0)

- Vocab updates can probably be indicated with minor version number changes (3.0.0 -> 3.1.0)

- Error/typo fixes can be versioned with a patch number (3.0.0 -> 3.0.1)
