### ISSUE TITLE
[Educational Resources schema] Add component_id

### ISSUE THREAD

**Issue by aclayton555** [mc2-center/data-models#26]
Discussed with Orion on 2023.11.15 as part of prep for upcoming educational resource curation session (https://sagebionetworks.jira.com/browse/CPO-910) and related activities to backpopulate and expanded curation of these resources. We have previously done this for Pubs, Tools, and Datasets, but intentionally had not done it for Educational Resources yet.

Wondering if it is possible to also tackle this related update to the Educational Resource schema in parallel: https://github.com/mc2-center/data-models/issues/24

**Comment by Bankso** [comment]
Educational resource schema is updated and backpopulation into Synapse projects is done. I'll take a look at issue #24 - that shouldn't be difficult to implement and integrate into the small number of entries we currently have.

**Comment by aclayton555** [comment]
This is great! THANK YOU. And I see the MC2 Center Affiliate Resources project that was created for the non-grant specific resources!!
