### ISSUE TITLE
CPO-813/CPO-816 Late 2023 grant curation-related updates to data model

### ISSUE THREAD

**Issue by aclayton555** [mc2-center/data-models#28]
Late 2023 grant curation: https://sagebionetworks.jira.com/browse/CPO-813

@aditigopalan  I added information on 10 new grants to be ingressed and displayed on the CCKP to the manifest linked in the above Jira issue. In order to ingress these and pass validation, however, we need to update the data model in a couple of places with any new terms.

I think the summary of updates includes the following:

- [x]  Add the following new grant numbers as valid values for all 'grant number' related attributes: CA280984, CA280849, CA280829, CA284090, CA284086, CA274504, CA283114, CA274507, CA274506, CA274511
- [x]  Add the following as a valid value for the attribute Grant Institution Name: Washington University in St. Louis
- [x]  Add the following as a valid value for the attribute Grant Institution Alias: WUSTL

Attempting to submit the manifest might also flag some additional updates needed. 

Is it possible to incorporate these updates into a data model release by the end of November 2023, complimentary to closing out this issue: https://github.com/mc2-center/data-models/issues/20

**Comment by aditigopalan** [comment]
Done! Just want to make sure we get another set of eyes on this before merging, @Bankso please review this when you can

**Comment by aclayton555** [comment]
@aditigopalan is there a way to link the PR for review to this issue?

**Comment by aclayton555** [comment]
@aditigopalan apologies, but we also just learned of one more grant number to include in this round. Could you please add CA282451 as valid values for all 'grant number' related attributes?

**Comment by aditigopalan** [comment]
Done, there is now a joint PR open pending review (#32) for Issues #31 and #28

Incorporated in [v23.12.1](https://github.com/mc2-center/data-models/releases/tag/v23.12.1)
