### ISSUE TITLE
[GrantView] Add additional attributes on start date and status

### ISSUE THREAD

**Issue by aclayton555** [mc2-center/data-models#31]
We would like some attributes to the GranView schema to provide information on grant start dates and status. This information will help us understand the activity status of grants, which will support onboarding/offboarding communications, and resource curation/engagement planning.

Attributes to add:

- [x] `Grant Start Date` - this should be REQUIRED and validated as a date, ideally in YYYY-MM-DD format (see schematic validation rule here: https://sagebionetworks.jira.com/wiki/spaces/SCHEM/pages/2645262364/Data+Model+Validation+Rules#date) . A description for this attribute can be, "The start date of the grant"
- [x] `NIH RePORTER Link` - this should be REQUIRED and validated as a URL (see schematic validation rule here: https://sagebionetworks.jira.com/wiki/spaces/SCHEM/pages/2645262364/Data+Model+Validation+Rules#URL-Validation-Type). A description for this attribute can be, "Link to the search results for this grant number on the NIH Reporter website"
- [x] `Duration of Funding` - this should be OPTIONAL. A description for this attribute can be, "Duration of the funding period, in years"
- [x] `Duration of Data Embargo` - this should be OPTIONAL. A description for this attribute can be, "Duration that the data are embargoed, in months"

@aditigopalan any chance we could also add these to the data model on time for our Dec release?

**Comment by jaybee84** [comment]
@aclayton555 @Bankso i had one other thought after the meeting ended. Is this data model specific for MC2 or would it be something that can later be potentially generalized to other data models across projects? 

The reason I ask is that some projects track grant end dates/embargo dates ( like NF) and if this data model forms the basis for something that can be reused in other projects, adding these attributes might be useful. We don't have to enforce these attributes in MC2, but if we have them as optional maybe NF can reuse this data model if they want and make it required on their end. Just thinking about generalizable solutions :)

**Comment by aclayton555** [comment]
I think this data model is currently specific to MC2, but there's nothing stopping adoption of this across projects. I know MC2 has contributed input into the ongoing common data model work with the data modelling group, so presumably a generalizable grant schema will emerge from that effort. Since we don't have the use case for end date or embargo in MC2, Jineta, can you advise on the attributes you think would be helpful to include in the schema at this phase (ie what are the attributes team like NF are tracking for grants)? As you mention, we could leave them optional for MC2 since we won't use them, but that would put them in place for others to use if they wanted to adopt this model.

**Comment by jaybee84** [comment]
I can think of the following currently:
1) duration of funding (let's us automatically calculate grant end date)
2) duration of data embargo after end date (lets us automatically calculate embargo end date)

**Comment by aclayton555** [comment]
thanks Jineta! Are these typically captured in months, years, etc?

**Comment by jaybee84** [comment]
1) duration of funding - years
2) duration of data embargo - months (varies between funders, some mandate months, some say years)

**Comment by aclayton555** [comment]
thanks JIneta - can you clarify the 'duration of embargo' attribute and how this should be described? e.g. "Duration of embargo from grant end date...", "Duration of embargo from publication...". 

If the value for this is "1 year," is this helpful without a point of reference (i.e. 1 year from X...)?

OR, does this attribute effectively represent a count down to the end of embargo and data access, in which case, rather than a duration could this be `embargo end date` or `embargoed until` ?

**Comment by aditigopalan** [comment]
@aclayton555 @jaybee84 I currently have the changes incorporated as on #32 :

- `Duration of Funding` - this should be OPTIONAL. A description for this attribute can be, "Duration of the funding period, in years"
-  `Duration of Data Embargo` - this should be OPTIONAL. A description for this attribute can be, "Duration that the data are embargoed, in months"

Any changes should be a quick fix so I am moving this to "In Progress"

**Comment by jaybee84** [comment]
@aclayton555 Sorry for the delay in my response. 

"Duration of embargo from grant end date..." seems most appropriate. Publication is generally when embargo is lifted. If there is not publication that is when the embargo duration from grant end date will come into play.

`embargo end date` is probably a better choice to keep it simple.

**Comment by aclayton555** [comment]
Thanks Jineta!

@aditigopalan based on this, I propose we update `Duration of Data Embargo` to:
`Embargo End Date` - This should be OPTIONAL and validated as a date, ideally in YYYY-MM-DD format (see schematic validation rule here: https://sagebionetworks.jira.com/wiki/spaces/SCHEM/pages/2645262364/Data+Model+Validation+Rules#date) . A description for this attribute can be, "Date at which an embargo on related resources had lifted"

**Comment by aditigopalan** [comment]
Done, changes included in [v23.12.1](https://github.com/mc2-center/data-models/releases/tag/v23.12.1)
