### ISSUE TITLE
[GrantView] Add attributes on Synapse project and team

### ISSUE THREAD

**Issue by aclayton555** [mc2-center/data-models#38]
We would like two new attributes to the GrantView schema to incorporate links to grant-based Synapse projects and teams into the grant metadata. This will help centralize grant-based Synapse project and team related information to support navigation by MC2 Center team members, contributors, and external portal users. Our current grant curation workflow involves creating Synapse projects and teams after we ingress grant metadata, which results in the links to these resources being uncoupled from the grant metadata. We are proposing to instead create grant-based Synapse projects and teams as part of the grant curation process, so these links can be incorporated into the metadata. This will allow centralization of this information in the respective admin and portal tables, which also supports a couple of uses below.

- [Immediate] With grant-based Synapse project and team linked captured as part of the grant metadata, this will help with designing and automating our community curation emails with links to grant-based projects. Additionally, we can leverage team membership to send these email.
- [Longer term] With grant-based Synapse project and team linked captured as part of the grant metadata, we have the option to surface this information from the CCKP grant cards and details pages to support user navigation to Synapse resources. Although this surfaces these links to these projects and teams publicly, this is in accordance with existing procedure and expectations that the MC2 Center will approve requests to access grant-based Synapse teams (i.e. access will still be restricted). However this will help with future navigation from the CCKP to Synapse projects where specific resources have been shared. 

Attributes to add:

- [x]  `Grant Synapse Project `- this should be REQUIRED. I think this could be validated as a URL???? A description for this attribute can be, "The Synapse project associated with the grant, created by the MC2 Center"
- [x] `Grant Synapse Team` - this should be REQUIRED. as above, I think this could be validated as a URL???? A description for this attribute can be, "The Synapse team associated with the grant, created by the MC2 Center"

**Comment by aditigopalan** [comment]
Done, @Bankso please review #39
