### ISSUE TITLE
Establish and document nomenclature for data model release versions

### ISSUE THREAD

**Issue by aclayton555** [mc2-center/data-models#45]
Discussed during 24-1 sprint kick-off on 2024.01.05:. Possible approaches:

- v[year].[month].[release number] - this version is used for HTAN data model releases, and is also used by FAIR for schematic and DCA releases.

- OR, take software approach of designating major vs minor patches (major.minor.patches-date) - e.g. 1.1.0-202401 . This approach would be more intuitive for devs and is complemented by the release notes including information on date of release.

Group agreed to adopt latter software approach. Action required to **define and document** what constitutes major vs minor vs patches, and how this nomenclature should be adopted for the MC2 data model.

Consider also standard approach for what is included in release notes. in addition to relevant issues/PR incorporated into each release, would be helpful to also document which version of schematic and DCA the released data model is level with (at the time of release)

@aditigopalan and @jaybee84 feel free to discuss this further in comments about how we define these and where this should be documented.

**Comment by aditigopalan** [comment]
@jaybee84 You may have mentioned this, but where do you think we should include this information?

**Comment by jaybee84** [comment]
Since the group decided to adopt the software versions approach from the next release, the nomenclature of this release tag should be documented in the Readme of the repo. It would be great to highlight that the next versions will follow the software versioning norms so that people know what to expect.

**Comment by aditigopalan** [comment]
@jaybee84 thank you! I added you as reviewer on #52 , please let me know if this works!

**Comment by aditigopalan** [comment]
@jaybee84 just checking in -- have you had the chance to review?

**Comment by jaybee84** [comment]
@aditigopalan Thanks for the reminder. Done.
