### ISSUE TITLE
Tidy up branches in data models repo

### ISSUE THREAD

**Issue by aclayton555** [mc2-center/data-models#46]
Review and tidy these up, as needed. Consider any documentation or guidance that we want to add around branches and branch usage for this repo.

**Comment by Bankso** [comment]
The following unused and feature related branches were removed:
- data-models (stale/no longer in use)
- nov-updates-ob (previously merged feature)
- ste-model (previously merged feature)
- minimal-models (no longer needed)

The remaining branches (use moving forward):
- data-models-dev (staging repo for gathering all model updates related to current release/sprint)
- main (production model, used to create releases)

For model development moving forward, I propose that: 
- we follow the [Contribution Guide in the MC2 onboarding docs](https://docs.google.com/document/d/107pEHo6U6yMu9mtViuQe0Ed1yVruFebmvhm_c-j8jI4/edit#heading=h.9g5a2ryv7kdk)
- use issue-based naming of branches, where applicable (e.g., 46-tidy-branches)
- create PRs to merge the feature/issue branches for the sprint into data-models-dev 
- related to issue #40, we can run data model checks on the dev branch, to minimize the chance of errors being propagated to the main repo
- after all PRs are merged and the dev branch passes all checks, merge dev --> main and create the new release, update the DCA config, etc. ([steps 6 and 7](https://docs.google.com/spreadsheets/d/1TzySDqeqOg38p6C3pZwGterM-j6A2n5hundDiwDg9nA/edit#gid=0&range=A7:A8) in the curation workflow defined previously)

**Comment by aclayton555** [comment]
Comments above to be included in further procedures/documentation, tracked in https://github.com/mc2-center/data-models/issues/51
