### ISSUE TITLE
Create template for PRs to automate branch deletion/tidiness

### ISSUE THREAD

**Issue by aclayton555** [mc2-center/data-models#47]
During our 24-1 sprint kick-off on 2024.01.05, Verena notes that there options to create a template for PRs that, upon PR merging, can help support automation around branch deletion. This will help support efforts to keep our branches tidy in this repo.

Can the template also ensure linkage between a PR and its related issues?

**Comment by vpchung** [comment]
## 1/5 update:

I have updated the repo settings to automatically delete feature branches once a PR has been merged:

![Image](https://github.com/mc2-center/data-models/assets/9377970/8c48069b-3706-4ff6-a85a-8017ce956078)

I will now create a couple of templates, including a PR template, a bug report template, and a release template.

**Comment by vpchung** [comment]
## 1/5 update (again)

Templates have been created!

**PR Template**
![Image](https://github.com/mc2-center/data-models/assets/9377970/cc3d2f28-eeab-491b-a19e-ab9c7ba38bf6)

Depending on which file(s) have been modified, code reviewers will be auto-assigned based on [code ownership](https://github.com/mc2-center/data-models/blob/main/.github/CODEOWNERS).

**Bug Template**
This template will auto-assign @aditigopalan as the addressee.  I can update this person as needed.

![Image](https://github.com/mc2-center/data-models/assets/9377970/464fe118-360a-4815-8102-059800d7befe)
