### ISSUE TITLE
Confirm MC2 DCA is level with v23.12.1 MC2 Data Model release

### ISSUE THREAD

**Issue by aclayton555** [mc2-center/data-models#48]
As a final step in closing out our last release, please ensure the DCA has been updated to point to the latest data model.

In HTAN, this PR is typically the final step to close out our release sprint cycle. An example of this can be found here: https://github.com/Sage-Bionetworks/data_curator_config/pull/139

**Comment by aditigopalan** [comment]
Updated to reflect v23.12.1, see https://github.com/mc2-center/data_curator_config/pull/3
