### ISSUE TITLE
Write up protocol for data model development, update, and release

### ISSUE THREAD

**Issue by Bankso** [mc2-center/data-models#51]
As a complement to the MC2 Center curation workflow, it would be helpful to write step-by-step protocols for developing data model features, updating the data model repo, creating model releases, and any other data model maintenance processes. Initial plan is to surface protocols in the readme for the data models repo.

**Comment by Bankso** [comment]
Note that part of my comment on issue #46 covers some the basics for what to include in the readme/protocol

**Comment by Bankso** [comment]
Issue #72 outlines the release portion of these protocols, so my current plan is to take that and expand it into step-by-step instructions for the read me.

**Comment by aclayton555** [comment]
Confirming this work will roll into 24-3 sprint.

**Comment by Bankso** [comment]
Fixed by PR #94
