### ISSUE TITLE
Scope/query updates when creating projects and tables

### ISSUE THREAD

**Issue by Bankso** [mc2-center/data-models#57]
Establish a protocol for updating MC2 Synapse infrastructure at different points in the model update/curation cycle.

Situations to address (non-exhaustive):
- When adding new Synapse projects for the MC2 Center --> scopes for master fileview and all tables should be updated
- When creating new tables in MC2 Center Synapse projects --> defining SQL for materialized views must be updated and new UNION tables must be created for any new metadata type

**Comment by Bankso** [comment]
All tables reference and UNION tables can be updated by scripts used to generate initial tables and are available in the mc2-center-dcc repo
Master fileview was updated by hand, but can be updated in a similar fashion to other view tables. This will really only need to be done when new projects are added, though, so the need for automation is minimal.
Since we have solutions for the points I mentioned, I'll close this and reopen if we decide to change our approach.

**Comment by aclayton555** [comment]
just adding assignee to this close ticket to help with metrics reporting through GH projects. Ignore this notification
