### ISSUE TITLE
Data model documentation refinements

### ISSUE THREAD

**Issue by Bankso** [mc2-center/data-models#68]
Following https://github.com/mc2-center/data-models/issues/49, https://github.com/mc2-center/data-models/pull/66 and in addition to https://github.com/mc2-center/data-models/issues/67

Initial deployment here: https://mc2-center.github.io/data-models/

Ideas for changes/additions to the data model documentation (in no particular order):

1. for any component or valid value table, include the type and description alongside the table name.
   - General form example:
      - type: name
         - description 
   - Specific example:
      - Attribute: Dataset Assay
         - the experimental assay associated with the content in the dataset
2. add a template/model table that shows the component/data type, description of the component, and link to the component attribute table
3. in attribute tables, add a link to the valid values associated with each attribute
4. show the template/component directory on the home page and move the term dictionary to the second header tab
5. modify the term dictionary to display the following:
   - Components (or Data Types, Data Models?) --> link to table listing all components
      - list component names and links to attribute tables
   - Attributes --> link to table listing all attributes
      - list attribute names, which link to row in attribute table
   - Valid Values --> link to tables listing all valid values by type
      - list valid value types in alphabetical order, linking to table associated with type

**Comment by vpchung** [comment]
## 3/11/24 update

PR is ready for review ✨
