### ISSUE TITLE
[release] 5.1.1

### ISSUE THREAD

**Issue by Bankso** [mc2-center/data-models#72]
## Checklist
This checklist covers the post-curation steps that should be performed when releasing a new data model version and syncing content to the Cancer Complexity Knowledge Portal.

### Data model
- [x] Add updates to a new branch in the data-models repo
- [x] Make a PR to merge updates into main
- [x] Verify CSV and JSON-LD were updated and added to branch or build and add manually
- [x] Build manifest templates in xlsx format and store in "templates" folder
- [x] Review and merge PR to main
- [x] Release new data model version

### Data Curator Config
- [x] Create new feature branch
- [x] Update data model and dca-template-config.json version number in data_curator_config/MC2/dca_config.json
- [x] Copy templates to display in DCA from data-models/templates to data_curator_config/MC2/templates
- [x] Ensure any templates that should be listed in the DCA are provided in data-models/dca_config/dca-template-config.json
- [x] Merge feature branch into data_curator_config/prod
- [x] Make a PR to Sage-Bionetworks/data_curator_config/prod

### Synapse
- [x] Process and upload metadata to grant-based Synapse projects (if needed)
- [x] Validate and filter the union tables
- [x] Upload CSVs of the final data to be synced
- [x] Sync CSVs to the portal tables
 

 ## Additional comments
CSVs are available in this folder: https://www.synapse.org/#!Synapse:syn53461903
The sync_publications.py script has been updated to work with PublicationView CSVs ([PR here](https://github.com/mc2-center/mc2-center-dcc/pull/40)), but DatasetView, ToolView, and EducationalResource scripts are not yet updated.

**Comment by aditigopalan** [comment]
@Bankso released v5.1.1

**Comment by Bankso** [comment]
DCA config updated to v5.1.1 data model and PR to merge into Sage-Bionetworks/data_curator_config is [here](https://github.com/Sage-Bionetworks/data_curator_config/pull/148)

PR has been merged. I will proceed with testing DCA manifest generation, validation, and submission.

**Comment by aclayton555** [comment]
@aditigopalan should the data model release v5.1.1 be marked as the "latest" release in the repo (looks like the repo still has v.4.1.0 denoted as the latest). Not sure if there is a way to have the latest release labelled accordingly by default?

**Comment by aditigopalan** [comment]
@Bankso @vpchung closing because I think this is wrapped up
