### ISSUE TITLE
[feat] Automate draft release

### ISSUE THREAD

**Issue by vpchung** [mc2-center/data-models#75]
As an internal data manager for MC2 Center, I would like to automate the following step(s) of the curation workflow:

* draft a release whenever a PR is pushed to the data model

**Comment by vpchung** [comment]
## 3/5/2024 update

A release for a data model needs to happen before new manifests can be validated and uploaded to Synapse.  Therefore, we can not have a workflow that will automate the release draft _and_ portal sync.

For now, the workflow should only focus on creating the release draft, then run the [portal sync workflow](https://github.com/mc2-center/mc2-center-dcc/actions/workflows/sync-to-portal.yml) manually once manifests are ready.

**Comment by aclayton555** [comment]
After a data model release, there is a step of filing a PR with FAIR to update our release tag in the DCA config. This workflow will create the draft of the release. Pushing the actual release will still happen on demand.
