### ISSUE TITLE
Documentation - Community Curation

### ISSUE THREAD

**Issue by aditigopalan** [mc2-center/data-models#86]
Following the portal sync and backpopulation initiatives, this ticket tracks engagement with contributors for feedback.

Action items: 

- [x] Review documentation and tutorial videos on Confluence/ Loom
  - [x] [Documentation on Confluence](https://sagebionetworks.jira.com/wiki/spaces/CCKPD/pages/3049095269/Community+Curation)
  - [x] [Confirming your resources](https://www.loom.com/share/a7dc474cdf54466fb2d46e6ac241c343?sid=419bbabc-0e4a-4b41-b7f3-631148de5c58)
  - [x] [Modifying resources: Publications](https://www.loom.com/share/3a445aebde66462380c8c8c4fe6c1a51?sid=a3744fe5-19a1-4f8c-bc47-61d013bea85f)
  - [x] [Modifying resources: Datasets](https://www.loom.com/share/a7e00ba5997346fe8f128c61c4a2d755?sid=814320c1-47bb-4d63-bb1f-fa684497628b)
  - [x] [Modifying resources: Tools](https://www.loom.com/share/5f11b7366da1483685afe53ef3d133a8?sid=c7d81815-857e-4296-92f0-c6c4b91d50fd)
- [x] Identify 10 data managers/ PIs to contact about documentation to get feedback on the process (DMOps group)
- [x] Discuss appropriate timeline for feedback process
- [x] Generate [email template](https://docs.google.com/document/d/1l1BnkQj5_KwIgkxhnGMg6GRflwANiz-PIJW50KMsyt0/edit?usp=sharing) 
- [x] Reach out to contributors, document in email tracker

Future Considerations:
Explore the possibility of automating emails (work in progress) and leverage the data managers operation group for engagement.

**Comment by aditigopalan** [comment]
@aclayton555 @Bankso I just linked our videos/ documentation directly. Could you please review so we can proceed with final edits?

**Comment by aditigopalan** [comment]
I also drafted an email template, please let me know what you think!

**Comment by aditigopalan** [comment]
Based on discussion during 3/28

**Comment by aditigopalan** [comment]
The docs are on separate pages now! @aclayton555 @Bankso let me know if there's anything else we should do before we wrap up this sprint!

**Comment by aclayton555** [comment]
Proceed to sync today to give an idea of what this looks like, then Aditi will make additional tweaks.

Over the next sprint, consider organizing this further to split portal UX vs contribution UX

**Comment by aclayton555** [comment]
Preview before going live: https://help.cancercomplexity.synapse.org/~preview-fe0bdb18-cbd7-4ec2-8ac8-5d7f18f9b214/doc/

**Comment by aclayton555** [comment]
Team to review backend confluence and add final comments. Aim to push live by the end of this week to be able to include a blurb in next week's newsletter.

**Comment by aclayton555** [comment]
@aditigopalan do you plan to send a follow-up to the DM Ops groups with requested actions to review our new docs? Maybe with a deadline for review?
