### ISSUE TITLE
[docs] Fill out the Home and Next Steps pages

### ISSUE THREAD

**Issue by vpchung** [mc2-center/data-models#92]
The docs site could use some love on the [landing page](https://mc2-center.github.io/data-models/) and the [Next Steps](https://mc2-center.github.io/data-models/next-steps/) page.

**Comment by vpchung** [comment]
CC @aclayton555 for awareness

**Comment by aclayton555** [comment]
Once we have the first iteration of the community curation docs up on the scroll viewport, would be good to have a "return to curation docs" button within the standards pages to streamline navigation back to these.

**Comment by aclayton555** [comment]
Change "Contribute" tab to "Contribute to the Data Model"
Also, move Next Steps tab to home page and include link oout to new page on CCKP docs
