### ISSUE TITLE
Update script for mapping annotations to latest standard terms

### ISSUE THREAD

**Issue by vpchung** [mc2-center/data-models#99]
More context: https://sagebionetworks.jira.com/browse/CPO-206

**Comment by vpchung** [comment]
Script to update annotations to latest standard term is being updated in this draft PR: https://github.com/mc2-center/mc2-center-dcc/pull/69

**Comment by vpchung** [comment]
[PR is now ready for review!](https://github.com/mc2-center/mc2-center-dcc/pull/69)

**Comment by aclayton555** [comment]
24-6 close out: @vpchung to run a few more tests to confirm following merge. Proceed to close when complete.
